### ISSUE TITLE
Hightlight in search result

### ISSUE THREAD

**Issue by Gabilabrebi** [SubC4i/Sublime-MavensMate-Monokai#3]
Hello

First i would like to say that this theme is by far the one that matches Sublime text 4 the best by far 👍 

I think there is an issue when selecting text inside a search result

![image](https://github.com/SubC4i/Sublime-MavensMate-Monokai/assets/39853761/eb8e7f78-c70f-4f26-9bcb-062676420ef8)

Here i search for "test" and i selected "te". I cannot see what part of the searched string is selected.

**Comment by SubC4i** [comment]
Thanks so much!

I've looked into the issue you've described and it appears the background color used for findMatch needs more opacity in order for the selection highlight color to shine through.  Here's a screenshot from what I've tested thus far.  If this ends up looking good, then I can generate a new version and release an update for the extension.

![Snap 2023-05-17 at 16 59 00](https://github.com/SubC4i/Sublime-MavensMate-Monokai/assets/32463601/5150e768-3de1-4d0a-9f44-258635b82416)

**Comment by Gabilabrebi** [comment]
Hello

It looks perfect to me. Exactly what i was looking for  ;)

**Comment by SubC4i** [comment]
New version with fix has been published.  Also updated display name to "SFDX Monokai Sublime".  Please let me know if the display name change caused any confusion.

**Comment by SubC4i** [comment]
Latest version with fix is available as v1.0.1 on VS Code Marketplace.
